### PR TITLE
Fix for issue #10

### PR DESCRIPTION
**Pull request by alexargo**
This fixes paths with strange characters ( parenthesis, spaces, etc). I also added some debugging code to see EXACTLY what is failing when trying to debug.

### CODE REVIEW

**Comment by jasperblues** [comment]
Thanks so much @alexargo. Would you like me to add you as a contributor on the ReadMe?

**Comment by alexargo** [comment]
I won't complain. :)

**Comment by jasperblues** [comment]
Done :)

**Comment by jasperblues** [comment]
Hmmmm. . . this PR seemed to break one of our local projects. Had to revert temporarily. Need to use both projects as a test case.

**Pull request merged**
