### PR TITLE
Leave lcov files around for someone to use if they see fit

### PR DESCRIPTION
**Pull request by alexargo**
Moved lcov output files to "data" folder in reportLocation folder in case someone wants to use it for something else.

### CODE REVIEW

**Comment by jasperblues** [comment]
:+1: Great

**Comment by alexargo** [comment]
Found a bug, and tweaked this a little to add a command line option for only generate lcov data, no report. Will have a new pull request soon. Great that closed it?

**Comment by jasperblues** [comment]
I mean great work. Do you want push access? Let me know if you push and I can regression test our current builds.

**Comment by alexargo** [comment]
Sure. I think I'll have this running in my CI setup for a while, so if there are some other tweaks or features I add would be nice to contribute back.

**Pull request closed without merging**
